### ISSUE TITLE
MovingWorld causes SpongeForge to crash.

### ISSUE THREAD

**Issue by darkevilmac** [elytra/MovingWorld#21]
Related to this method if @simon816 is correct, https://github.com/darkevilmac/MovingWorld/blob/6db0b6e30da6c8e2991db08ab5f60012c1b5dfc7/src/main/java/darkevilmac/movingworld/common/asm/coremod/MovingWorldCoreMod.java#L26

**Comment by darkevilmac** [comment]
New crash http://pastebin.com/h6eLhyJh

**Comment by simon816** [comment]
^ @Mumfrey this is what I get when running latest SpongeForge and latest MovingWorld

**Comment by simon816** [comment]
So it turns out that my fix only actually fixed it in a development environment (eclipse). This still seems to be happening in an obfuscated environment.

**Comment by Inscrutable** [comment]
Indeed. It still seems to break SpongeForge (I just tested SF 1118). Any other ideas, @simon816 ?

**Comment by simon816** [comment]
I think the problem is because MovingWorld loads before SpongeForge. @Mumfrey any ideas? This issue seems to be the same problem: https://github.com/SpongePowered/SpongeForge/issues/511

**Comment by darkevilmac** [comment]
@simon816 Just updated Mixins again, not sure if there's been any changes that might fix things since the last update but could you give it a try when Sponge updates as well?

**Comment by darkevilmac** [comment]
@Mumfrey From what I understand by looking at the issue listed above there's nothing I can do at the moment correct? If there's some sort of workaround I could try and implement let me know.

**Comment by Mumfrey** [comment]
The work-around would be basically making sure that Sponge and MovingWorld are loaded in the right order. The simplest way of doing that would be either renaming the Sponge jar with an underscore at the beginning like `_sponge.whatever.jar` or renaming MovingWorld jar to `zzzMovingWorld.jar`.

Basically the problem boils down to coremods being initialised in alphabetical order and **not** priority order, we are pursuing solutions to this internally with the relevant people.

**Comment by darkevilmac** [comment]
Ah, I see. I'll leave the issue open for now and close it when that's fixed then. In the meantime I'll rename my curse downloads.
